version: '3'

services:
  afeefa_backend_mysql:
    container_name: afeefa_backend_mysql
    image: mysql:5.7
    hostname: mysql
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: afeefa_dev
    command: --default-authentication-plugin=mysql_native_password --sql_mode=""
    volumes:
      - afeefa_backend_mysql:/var/lib/mysql
    ports:
      - "9907:3306"

  afeefa_backend_api:
    container_name: afeefa_backend_api
    image: afeefa_backend_api
    hostname: backend-api
    tty: true
    depends_on:
      - afeefa_backend_mysql
    volumes:
      - afeefa-backend-api:/app/:nocopy
    build:
      context: '.'
      dockerfile: 'ruby/Dockerfile'
    ports:
      - "${PORT_EXTERN}:${PORT_INTERN}"

volumes:
  afeefa_backend_mysql:
    driver: local
  afeefa-backend-api:
    external: true
  afeefa-backend-ui:
    external: true
  afeefa-frontend-api:
    external: true
  afeefa-frontend-ui:
    external: true
  afeefa-ui-datastore:
    external: true
  afeefa-message-api:
    external: true
  afeefa-wisdom-api:
    external: true
